name: animus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    bloc: ^8.1.3
    dio: ^5.4.1
    equatable: ^2.0.5
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.4
    flutter_carousel_widget: ^2.2.0
    get: ^4.6.6
    google_fonts: ^6.2.1
    json_annotation: ^4.8.1
    logger: ^2.1.0
    number_paginator: ^0.4.1
    retrofit: ^4.1.0
    skeletonizer: ^1.1.1

dev_dependencies:
    retrofit_generator: ">=7.0.0 <8.0.0"
    build_runner: ^2.4.8
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - lib/images/
